esphome:
  name: "fermenter2"
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fermenter2 Fallback Hotspot"
    password: !secret wifi_backup_password

captive_portal:

switch:
  - platform: gpio
    name: "Fermenter 2 LED"
    inverted: true
    pin: D4
  - platform: gpio
    id: freezer_power
    name: "Fermenter 2 Freezer Power"
    pin: D5

one_wire:
  - platform: gpio
    pin: D3

sensor:
  - platform: dallas_temp
    name: "Fermenter 2 temperature"
    id: fermenter_temp
    update_interval: 5s

# Fermenter thermostat
climate:
  - name: "Fermenter 2 thermostat"
    id: fermenter_thermostat
    default_preset: home
    platform: thermostat
    visual:
      min_temperature: -1
      max_temperature: 40
      temperature_step: 1
    sensor: fermenter_temp    
    preset:
      # Standard presets
      - name: home
        default_target_temperature_high: 10
    startup_delay: True
    cool_deadband: 0.5
    cool_overrun: 0.5
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_idle_time: 30s
    cool_action:
      - switch.turn_on: freezer_power
    idle_action:
      - switch.turn_off: freezer_power
